### ISSUE TITLE
Testing Thymeleaf (not Thymesheet) views

### ISSUE THREAD

**Issue by paulspencerwilliams** [connect-group/thymeleaf-tdd#4]
Hi, having had a little play, I've struggled to get tests to pass against Thymeleaf views. In your sample Thymesheet application which obviously works, as soon as the TSS folder is removed, .html views are no longer found. Have you tried these tests against raw Thymeleaf?

**Comment by paulspencerwilliams** [comment]
Having followed the readme rather than diffing the sample project against a simple Spring Boot project, I can confirm this does work with raw Thymeleaf. Cheers for a great library!

**Comment by 4dz** [comment]
Thanks, glad you got it working :)
